name: build & bublish container image

on:

  pull_request:

  push:

defaults:
  run:
    shell: bash

jobs:

  main:

    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build container image
      run: buildah build --layers -t ghcr.io/yrro/dirsrv-exporter

    - name: Push image
      uses: redhat-actions/push-to-registry@v2
      with:
        tags: ghcr.io/yrro/dirsrv-exporter:latest
        username: _ignored_
        password: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' # NOT a security check!
