name: build & publish container image

on:

  pull_request:

  push:

defaults:
  run:
    shell: bash

jobs:

  main:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build container image
      run: buildah build --layers -t ghcr.io/yrro/dirsrv-exporter

    - name: Push image
      uses: redhat-actions/push-to-registry@v2
      with:
        tags: ghcr.io/yrro/dirsrv-exporter:latest
        username: _ignored_
        password: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' # NOT a security check!

  snyk:
    needs: main
    runs-on: ubuntu-latest
    steps:

    - name: Monitor image with Snyk
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: monitor
        image: ghcr.io/yrro/dirsrv-exporter:latest

  container-retention-policy:
    needs: main
    runs-on: ubuntu-latest
    steps:

    - name: Prune old images
      uses: snok/container-retention-policy@v3.0.0
      with:
        image-names: dirsrv-exporter
        cut-off: '1m'
        keep-n-most-recent: 5
        account: user
        token: ${{ secrets.GITHUB_TOKEN }}
