name: build, publish, monitor container image

on:

  pull_request:

  push:

defaults:
  run:
    shell: bash

jobs:

  main:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build container image
      run: buildah build --layers -t quay.io/yrro/dirsrv-exporter

    - name: Push image
      id: push
      uses: redhat-actions/push-to-registry@v2
      with:
        tags: quay.io/yrro/dirsrv-exporter:latest
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
