name: post-push actions

on:

  registry_package:
    types:
    - published

defaults:
  run:
    shell: bash

jobs:

  post-push:

    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:

    - name: Monitor image with Snyk
      uses: snyk/actions/docker@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: monitor
        image: ghcr.io/yrro/dirsrv-exporter:latest

    - name: Prune old images
      uses: snok/container-retention-policy@v2
      with:
        image-names: dirsrv-exporter
        cut-off: 1 minute ago UTC
        keep-at-least: 5
        account-type: personal
        token: ${{ secrets.GITHUB_TOKEN }}
        token-type: github-token
      if: steps.push.outcome == 'success'
